---
deployment:
 tasks:
 - export DEPLOYPATH=/home/dejvokep/website/
 - /bin/cp -R public $DEPLOYPATH
 - /bin/cp -R views $DEPLOYPATH
 - /bin/cp fetch-data.js $DEPLOYPATH
 - /bin/cp index.js $DEPLOYPATH
 - /bin/cp LICENSE $DEPLOYPATH
 - /bin/cp package-lock.json $DEPLOYPATH
 - /bin/cp package.json $DEPLOYPATH
 - /bin/cp README.md $DEPLOYPATH